ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.cutter("gtlcore:optical_slice")
        .itemInputs("gtlcore:optical_wafer")
        .itemOutputs("16x gtlcore:optical_slice")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(560)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:exotic_chip")
        .itemInputs("gtlcore:exotic_wafer")
        .itemOutputs("4x gtlcore:exotic_chip")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:photocoated_hassium_wafer")
        .itemInputs("gtlcore:photocoated_hassium_boule")
        .itemOutputs("4x gtlcore:photocoated_hassium_wafer")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(280)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:bioware_chip")
        .itemInputs("gtlcore:bioware_boule")
        .itemOutputs("16x gtlcore:bioware_chip", "8x gtlcore:biological_cells")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(600)
        .cleanroom(CleanroomType.STERILE_CLEANROOM)

    gtr.cutter("gtlcore:taranium_wafer")
        .itemInputs("gtlcore:taranium_boule")
        .itemOutputs("64x gtlcore:taranium_wafer", "64x gtlcore:taranium_wafer")
        .EUt(122880)
        .duration(3200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:rutherfordium_neutronium_wafer")
        .itemInputs("gtlcore:rutherfordium_neutronium_boule")
        .itemOutputs("64x gtlcore:rutherfordium_neutronium_wafer", "32x gtlcore:rutherfordium_neutronium_wafer")
        .EUt(30720)
        .duration(3200)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:nm_chip")
        .itemInputs("gtlcore:nm_wafer")
        .itemOutputs("4x gtlcore:nm_chip")
        .EUt(30720)
        .duration(1800)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:pm_chip")
        .itemInputs("gtlcore:pm_wafer")
        .itemOutputs("4x gtlcore:pm_chip")
        .EUt(122880)
        .duration(1800)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:fm_chip")
        .itemInputs("gtlcore:fm_wafer")
        .itemOutputs("2x gtlcore:fm_chip")
        .EUt(524288)
        .duration(2700)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:optical_ram_chip")
        .itemInputs("gtlcore:optical_ram_wafer")
        .itemOutputs("32x gtlcore:optical_ram_chip")
        .EUt(122880)
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:exotic_ram_chip")
        .itemInputs("gtlcore:exotic_ram_wafer")
        .itemOutputs("32x gtlcore:exotic_ram_chip")
        .EUt(524288)
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:cosmic_ram_chip")
        .itemInputs("gtlcore:cosmic_ram_wafer")
        .itemOutputs("32x gtlcore:cosmic_ram_chip")
        .EUt(524288 * 4)
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:supracausal_ram_chip")
        .itemInputs("gtlcore:supracausal_ram_wafer")
        .itemOutputs("4x gtlcore:supracausal_ram_chip")
        .EUt(524288 * 16)
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.cutter("gtlcore:cosmic_soc")
        .itemInputs("gtlcore:cosmic_soc_wafer")
        .itemOutputs("8x gtlcore:cosmic_soc")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(900)
        .cleanroom(CleanroomType.CLEANROOM)
})