ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:hypercube")
        .itemInputs("12x gtceu:cosmicneutronium_rod", "24x gtceu:celestialtungsten_rod")
        .inputFluids("gtceu:exciteddtec 1000")
        .itemOutputs("gtlcore:hypercube")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(2400)
        .blastFurnaceTemp(30000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:chaos_plasma")
        .itemInputs("gtlcore:chaos_shard")
        .inputFluids("gtceu:dimensionallytranscendentresplendentcatalyst 1000", "gtceu:cosmic_mesh_plasma 1000")
        .outputFluids("gtceu:chaos_plasma 1000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(1600)
        .blastFurnaceTemp(32000)

    gtr.dimensionally_transcendent_plasma_forge("avaritia:infinity_catalyst")
        .itemInputs("64x gtlcore:contained_exotic_matter", "64x gtlcore:essentia_matter")
        .inputFluids("gtceu:infinity 1000", "gtceu:high_energy_quark_gluon_plasma 100000")
        .itemOutputs("avaritia:infinity_catalyst", "64x gtlcore:time_dilation_containment_unit")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(4800)
        .blastFurnaceTemp(32000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:transcendentmetal")
        .notConsumable("gtlcore:spacetime_catalyst")
        .itemInputs("gtlcore:hypercube")
        .inputFluids("gtceu:spacetime 100", "gtceu:tennessine 144")
        .outputFluids("gtceu:transcendentmetal 144", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(3200)
        .blastFurnaceTemp(36000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:cosmic_neutron_plasma_cell")
        .notConsumable("avaritia:infinity_catalyst")
        .itemInputs("5x gtlcore:extremely_durable_plasma_cell")
        .inputFluids("gtceu:uu_matter 1000000", "gtceu:dense_neutron_plasma 1000")
        .itemOutputs("5x gtlcore:cosmic_neutron_plasma_cell")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)
        .blastFurnaceTemp(28000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:crystalmatrix_plasma")
        .notConsumable("avaritia:infinity_catalyst")
        .itemInputs("avaritia:crystal_matrix")
        .inputFluids("gtceu:uu_matter 1000000", "gtceu:free_proton_gas 20000")
        .outputFluids("gtceu:crystalmatrix_plasma 10000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)
        .blastFurnaceTemp(28000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:infinity")
        .notConsumable("gtlcore:spacetime_catalyst")
        .inputFluids("gtceu:crystalmatrix_plasma 10000", "gtceu:cosmicneutronium 5000")
        .outputFluids("gtceu:infinity 1000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(4 * GTValues.VA[GTValues.MAX])
        .duration(1600)
        .blastFurnaceTemp(32000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:dimensionallytranscendentresidue")
        .inputFluids("gtceu:dimensionallytranscendentcrudecatalyst 100", "gtceu:raw_star_matter_plasma 100")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(400)
        .blastFurnaceTemp(36000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:spacetime_ingot")
        .notConsumable("64x kubejs:ingot_field_shape")
        .notConsumable("64x gtlcore:spacetimebendingcore")
        .inputFluids("gtceu:spacetime 1000", "gtceu:raw_star_matter_plasma 1000")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .itemOutputs("8x gtceu:spacetime_ingot")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(6400)
        .blastFurnaceTemp(62000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:spacetime")
        .notConsumable("gtlcore:spacetime_catalyst")
        .inputFluids("gtceu:infinity 100", "gtceu:hypogen 100")
        .outputFluids("gtceu:spacetime 200", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(4 * GTValues.VA[GTValues.MAX])
        .duration(1600)
        .blastFurnaceTemp(36000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:magnetohydrodynamicallyconstrainedstarmatter")
        .notConsumable("gtlcore:eternity_catalyst")
        .itemInputs("gtceu:eternity_nanoswarm")
        .chancedOutput("gtceu:contaminable_eternity_nanoswarm", 5000, 0)
        .inputFluids("gtceu:raw_star_matter_plasma 100000", "gtceu:exciteddtsc 100000")
        .outputFluids("gtceu:magnetohydrodynamicallyconstrainedstarmatter 100000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(1024 * GTValues.VA[GTValues.MAX])
        .duration(6400)
        .blastFurnaceTemp(81000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:dense_neutron_plasma")
        .notConsumable("avaritia:infinity_catalyst")
        .itemInputs("gtlcore:neutron_plasma_containment_cell")
        .inputFluids("gtceu:heavy_quark_degenerate_matter_plasma 10000", "gtceu:periodicium 1000")
        .outputFluids("gtceu:dense_neutron_plasma 10000", "gtceu:dimensionallytranscendentresidue 100")
        .itemOutputs("gtlcore:plasma_containment_cell")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)
        .blastFurnaceTemp(26000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:eternity")
        .notConsumable("gtlcore:eternity_catalyst")
        .itemInputs("avaritia:eternal_singularity")
        .inputFluids("gtceu:primordialmatter 1000", "gtceu:raw_star_matter_plasma 9000")
        .outputFluids("gtceu:eternity 10000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(16 * GTValues.VA[GTValues.MAX])
        .duration(4800)
        .blastFurnaceTemp(56000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:rhugnor")
        .notConsumable("avaritia:infinity_catalyst")
        .itemInputs("64x gtceu:energy_crystal")
        .inputFluids("gtceu:infinity 10000", "gtceu:quantum 10000")
        .outputFluids("gtceu:rhugnor 10000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(4 * GTValues.VA[GTValues.MAX])
        .duration(3600)
        .blastFurnaceTemp(36000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:hypogen")
        .notConsumable("avaritia:infinity_catalyst")
        .itemInputs("gtceu:quantumchromodynamically_confined_matter_block")
        .inputFluids("gtceu:rhugnor 10000", "gtceu:dragon_blood 10000")
        .outputFluids("gtceu:hypogen 10000", "gtceu:dimensionallytranscendentresidue 100")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(1200)
        .blastFurnaceTemp(26000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:infinity_glass")
        .itemInputs("gtlcore:black_body_naquadria_supersolid", "2x gtceu:infinity_dust")
        .inputFluids("gtceu:dimensionallytranscendentexoticcatalyst 1000", "gtceu:woods_glass 9216")
        .itemOutputs("gtlcore:infinity_glass")
        .EUt(4096 * GTValues.VA[GTValues.MAX])
        .duration(1600)
        .blastFurnaceTemp(88000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:create_casing")
        .itemInputs("gtceu:eternity_frame", "gtlcore:command_block_core")
        .inputFluids("gtceu:exciteddtsc 1000", "gtceu:primordialmatter 1000")
        .itemOutputs("gtlcore:create_casing")
        .EUt(16384 * GTValues.VA[GTValues.MAX])
        .duration(3200)
        .blastFurnaceTemp(96000)

    gtr.dimensionally_transcendent_plasma_forge("gtlcore:hypercube_1")
        .itemInputs("16x gtceu:transcendentmetal_rod", "gtlcore:quantum_anomaly")
        .inputFluids("gtceu:exciteddtec 1000", "gtceu:spatialfluid 1000")
        .itemOutputs("64x gtlcore:hypercube")
        .outputFluids("gtceu:dimensionallytranscendentresidue 100")
        .EUt(16 * GTValues.VA[GTValues.MAX])
        .duration(6400)
        .blastFurnaceTemp(62000)

    gtr.stellar_forge("gtlcore:eternity_dust")
        .itemInputs("4x gtlcore:quantum_chromodynamic_charge", "avaritia:eternal_singularity")
        .inputFluids("gtceu:primordialmatter 1000", "gtceu:dimensionallytranscendentresidue 1000")
        .itemOutputs("gtceu:eternity_dust")
        .outputFluids("gtceu:temporalfluid 1000")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)
        .addData("SCTier", 3)

    gtr.stellar_forge("gtlcore:temporalfluid")
        .itemInputs("4x gtlcore:quantum_chromodynamic_charge", "gtlcore:hypercube")
        .inputFluids("gtceu:spacetime 1000", "gtceu:dimensionallytranscendentresidue 100")
        .outputFluids("gtceu:temporalfluid 500", "gtceu:spatialfluid 500")
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)
        .addData("SCTier", 3)

    gtr.stellar_forge("gtlcore:cosmic_mesh_plasma")
        .itemInputs("gtlcore:quantum_chromodynamic_charge", "gtlcore:highly_dense_polymer_plate")
        .outputFluids("gtceu:cosmic_mesh_plasma 1000")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData("SCTier", 3)


    gtr.stellar_forge("gtlcore:exciteddtec")
        .itemInputs("gtlcore:quantum_chromodynamic_charge", "enderio:prescient_powder")
        .inputFluids("gtceu:dimensionallytranscendentexoticcatalyst 10000")
        .outputFluids("gtceu:exciteddtec 10000")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData("SCTier", 3)

    gtr.stellar_forge("gtlcore:neutron_plasma_containment_cell")
        .inputFluids("gtceu:neutronium 1000", "gtceu:heavy_lepton_mixture 1000")
        .itemInputs("gtlcore:naquadria_charge", "gtlcore:plasma_containment_cell")
        .itemOutputs("gtlcore:neutron_plasma_containment_cell")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData("SCTier", 1)

    gtr.stellar_forge("gtlcore:free_proton_gas")
        .itemInputs("gtlcore:naquadria_charge", "gtlcore:contained_high_density_protonic_matter")
        .outputFluids("gtceu:free_proton_gas 10000")
        .itemOutputs("gtlcore:time_dilation_containment_unit")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData("SCTier", 1)

    gtr.stellar_forge("gtlcore:enderium_plasma")
        .inputFluids("gtceu:ender_eye 2304", "gtceu:lead 2304", "gtceu:bismuth 2304", "gtceu:platinum 1152", "gtceu:liquid_ender_air 100000")
        .itemInputs("gtlcore:naquadria_charge", "enderio:ender_crystal_powder")
        .outputFluids("gtceu:enderium_plasma 2304")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData("SCTier", 1)

    gtr.stellar_forge("gtlcore:adamantium_plasma")
        .inputFluids("gtceu:orichalcum 576", "gtceu:tin 1024", "gtceu:antimony 864", "gtceu:iron 1152", "gtceu:mercury 1000")
        .itemInputs("gtlcore:naquadria_charge", "24x gtceu:bloodstone_dust")
        .outputFluids("gtceu:adamantium_plasma 2304")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData("SCTier", 1)

    gtr.stellar_forge("gtlcore:degenerate_rhenium_plasma")
        .itemInputs("gtlcore:naquadria_charge", "5x gtceu:double_rhenium_plate")
        .outputFluids("gtceu:degenerate_rhenium_plasma 10000")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData("SCTier", 1)

    gtr.stellar_forge("gtlcore:infuscolium_plasma")
        .inputFluids("gtceu:adamantine 2304", "gtceu:mana 10000")
        .itemInputs("gtlcore:naquadria_charge", "16x minecraft:end_crystal", "16x minecraft:popped_chorus_fruit")
        .outputFluids("gtceu:infuscolium_plasma 2304")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData("SCTier", 1)

    gtr.stellar_forge("gtlcore:legendarium_plasma")
        .inputFluids("gtceu:naquadriatictaranium 576", "gtceu:trinium 288", "gtceu:duranium 288", "gtceu:tritanium 288", "gtceu:orichalcum 288", "gtceu:mithril 288", "gtceu:adamantium 288", "gtceu:adamantine 288", "gtceu:vibranium 288")
        .itemInputs("gtlcore:leptonic_charge", "gtlcore:neutron_plasma_containment_cell")
        .outputFluids("gtceu:legendarium_plasma 2304")
        .itemOutputs("gtlcore:plasma_containment_cell")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData("SCTier", 2)

    gtr.stellar_forge("gtlcore:astraltitanium_plasma")
        .itemInputs("gtlcore:naquadria_charge")
        .inputFluids("gtceu:force 576", "gtceu:titanium 576", "gtceu:cobalt 288", "gtceu:copper 288", "gtceu:tritium 1000")
        .outputFluids("gtceu:astraltitanium_plasma 1000")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData("SCTier", 1)

    gtr.stellar_forge("gtlcore:celestialtungsten_plasma")
        .itemInputs("gtlcore:naquadria_charge")
        .inputFluids("gtceu:tartarite 576", "gtceu:tungsten 576", "gtceu:americium 288", "gtceu:titan_precision_steel 144", "gtceu:astraltitanium 144", "gtceu:xenon 1000")
        .outputFluids("gtceu:celestialtungsten_plasma 1000")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData("SCTier", 1)

    gtr.stellar_forge("gtlcore:quark_gluon_plasma")
        .itemInputs("gtlcore:leptonic_charge", "10x gtceu:degenerate_rhenium_dust")
        .outputFluids("gtceu:quark_gluon_plasma 10000")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData("SCTier", 2)

    gtr.stellar_forge("gtlcore:heavy_quark_degenerate_matter_plasma")
        .inputFluids("gtceu:heavy_quark_enriched_mixture 1152", "gtceu:flerovium 144", "gtceu:oganesson 144", "gtceu:hassium 144", "gtceu:deuterium 1000")
        .itemInputs("gtlcore:leptonic_charge")
        .outputFluids("gtceu:heavy_quark_degenerate_matter_plasma 1152")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData("SCTier", 2)

    gtr.stellar_forge("gtlcore:contained_high_density_protonic_matter")
        .itemInputs("gtlcore:leptonic_charge", "gtlcore:time_dilation_containment_unit", "gtlcore:charged_triplet_neutronium_sphere")
        .itemOutputs("gtlcore:contained_high_density_protonic_matter")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData("SCTier", 2)

    gtr.stellar_forge("gtlcore:crystalmatrix_plasma")
        .itemInputs("gtlcore:leptonic_charge", "avaritia:crystal_matrix", "16x gtlcore:corporeal_matter")
        .inputFluids("gtceu:free_proton_gas 20000")
        .outputFluids("gtceu:crystalmatrix_plasma 1000")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData("SCTier", 2)

    gtr.stellar_forge("gtlcore:starmetal_plasma")
        .itemInputs("gtlcore:leptonic_charge", "10x gtlcore:resonating_gem")
        .inputFluids("gtceu:free_proton_gas 1000", "gtceu:free_electron_gas 1000")
        .outputFluids("gtceu:starmetal_plasma 1000")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData("SCTier", 2)

    gtr.stellar_forge("gtlcore:high_energy_quark_gluon_plasma")
        .itemInputs("gtlcore:quantum_chromodynamic_charge", "10x gtceu:double_heavy_quark_degenerate_matter_plate", "enderio:pulsating_powder")
        .outputFluids("gtceu:high_energy_quark_gluon_plasma 2000")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData("SCTier", 2)

    gtr.stellar_forge("gtlcore:quantumchromodynamically_confined_matter_plasma")
        .itemInputs("gtlcore:quantum_chromodynamic_charge", "20x gtlcore:quantumchromodynamic_protective_plating")
        .outputFluids("gtceu:quantumchromodynamically_confined_matter_plasma 2000")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData("SCTier", 3)

    gtr.stellar_forge("gtlcore:dense_neutron_plasma")
        .inputFluids("gtceu:periodicium 2736", "gtceu:gluons 6000", "gtceu:heavy_lepton_mixture 6000")
        .itemInputs("gtlcore:quantum_chromodynamic_charge", "5x gtceu:neutronium_block", "5x gtceu:heavy_quark_degenerate_matter_block")
        .outputFluids("gtceu:dense_neutron_plasma 6000")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData("SCTier", 3)

    gtr.stellar_forge("gtlcore:extremely_durable_plasma_cell")
        .itemInputs("gtlcore:quantum_chromodynamic_charge", "2x gtlcore:dense_neutron_plasma_cell")
        .itemOutputs("gtlcore:cosmic_neutron_plasma_cell", "gtlcore:extremely_durable_plasma_cell")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData("SCTier", 3)

    gtr.stellar_forge("gtlcore:infinity_ingot")
        .inputFluids("gtceu:crystalmatrix 2000", "gtceu:cosmicneutronium 1000")
        .itemInputs("gtlcore:quantum_chromodynamic_charge", "enderio:vibrant_powder")
        .itemOutputs("gtceu:hot_infinity_ingot")
        .outputFluids("gtceu:infinity 10")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData("SCTier", 3)

    gtr.stellar_forge("gtlcore:contained_reissner_nordstrom_singularity")
        .itemInputs("gtlcore:naquadria_charge", "64x gtlcore:time_dilation_containment_unit", "64x gtlcore:charged_triplet_neutronium_sphere")
        .itemOutputs("64x gtlcore:contained_reissner_nordstrom_singularity")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData("SCTier", 1)

    gtr.stellar_forge("gtlcore:contained_kerr_newmann_singularity")
        .itemInputs("gtlcore:leptonic_charge", "64x gtlcore:contained_reissner_nordstrom_singularity")
        .itemOutputs("gtlcore:contained_kerr_newmann_singularity", "63x gtlcore:time_dilation_containment_unit")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData("SCTier", 2)

    gtr.stellar_forge("gtlcore:contained_exotic_matter")
        .itemInputs("gtlcore:leptonic_charge", "gtlcore:contained_high_density_protonic_matter", "9x gtceu:tiny_degenerate_rhenium_dust")
        .itemOutputs("gtlcore:contained_exotic_matter")
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(200)
        .addData("SCTier", 2)

    gtr.stellar_forge("gtlcore:recursively_folded_negative_space")
        .itemInputs("gtlcore:quantum_chromodynamic_charge", "2x gtlcore:macrowormhole_generator", "2x gtlcore:temporal_matter")
        .itemOutputs("gtlcore:recursively_folded_negative_space")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData("SCTier", 3)

    gtr.stellar_forge("gtlcore:eigenfolded_kerr_manifold")
        .itemInputs("gtlcore:quantum_chromodynamic_charge", "gtlcore:stabilized_wormhole_generator", "gtlcore:recursively_folded_negative_space")
        .itemOutputs("gtlcore:eigenfolded_kerr_manifold")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData("SCTier", 3)

    gtr.stellar_forge("gtlcore:ctc_computational_unit")
        .itemInputs("gtlcore:quantum_chromodynamic_charge", "gtlcore:eigenfolded_kerr_manifold", "gtlcore:ctc_computational_unit_container")
        .itemOutputs("gtlcore:ctc_computational_unit")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData("SCTier", 3)

    gtr.stellar_forge("gtlcore:dragon_heart")
        .itemInputs("gtlcore:naquadria_charge", "64x minecraft:dragon_egg", "gtceu:double_draconiumawakened_plate")
        .itemOutputs("gtlcore:dragon_heart")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData("SCTier", 1)

    gtr.stellar_forge("gtlcore:chaos_shard")
        .itemInputs("gtlcore:quantum_chromodynamic_charge", "gtlcore:infused_obsidian", "minecraft:bedrock")
        .inputFluids("gtceu:radox 1000")
        .itemOutputs("gtlcore:chaos_shard")
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(200)
        .addData("SCTier", 3)

    gtr.stellar_forge("gtlcore:actinium_superhydride_plasma")
        .itemInputs("gtlcore:naquadria_charge", "36x gtceu:atinium_hydride_dust")
        .inputFluids("gtceu:hydrogen 81000")
        .outputFluids("gtceu:actinium_superhydride_plasma 36000")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(200)
        .addData("SCTier", 1)

    gtr.ultimate_material_forge("gtlcore:proto_matter")
        .itemInputs("gtlcore:triplet_neutronium_sphere")
        .inputFluids("gtceu:uu_matter 1000")
        .itemOutputs("gtlcore:proto_matter")
        .chancedOutput("gtceu:neutronium_ingot", 6000, 0)
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(1600)

    gtr.ultimate_material_forge("gtlcore:pellet_antimatter")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:antihydrogen 10")
        .itemInputs("64x ae2:matter_ball", "gtceu:neutronium_nugget")
        .itemOutputs("gtlcore:pellet_antimatter")
        .chancedOutput("gtlcore:void_matter", 100, 0)
        .EUt(GTValues.VA[GTValues.UXV])
        .duration(2000)

    gtr.ultimate_material_forge("gtlcore:corporeal_matter")
        .itemInputs("gtlcore:proto_matter", "minecraft:iron_block")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:nihonium 100")
        .itemOutputs("gtlcore:corporeal_matter")
        .chancedOutput("gtceu:heavy_quark_degenerate_matter_nugget", 500, 0)
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(800)

    gtr.ultimate_material_forge("gtlcore:kinetic_matter")
        .itemInputs("gtlcore:corporeal_matter", "gtceu:tritanium_block")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:naquadria 1000")
        .itemOutputs("gtlcore:kinetic_matter")
        .chancedOutput("gtlcore:amorphous_matter", 200, 0)
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(600)

    gtr.ultimate_material_forge("gtlcore:amorphous_matter")
        .itemInputs("gtlcore:corporeal_matter", "gtceu:carbon_nanotubes_block")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:legendarium 1000")
        .itemOutputs("gtlcore:amorphous_matter")
        .chancedOutput("gtlcore:essentia_matter", 100, 0)
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(800)

    gtr.ultimate_material_forge("gtlcore:essentia_matter")
        .itemInputs("gtlcore:amorphous_matter", "gtceu:heavy_quark_degenerate_matter_block")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:quantumchromodynamically_confined_matter 1000")
        .itemOutputs("gtlcore:essentia_matter")
        .chancedOutput("gtlcore:dark_matter", 100, 0)
        .EUt(GTValues.VA[GTValues.OpV])
        .duration(1200)

    gtr.ultimate_material_forge("gtlcore:omni_matter")
        .itemInputs("gtlcore:essentia_matter", "gtlcore:kinetic_matter")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:dense_neutron_plasma 1000")
        .itemOutputs("gtlcore:omni_matter")
        .chancedOutput("gtceu:tiny_cosmicneutronium_dust", 1000, 0)
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(800)

    gtr.ultimate_material_forge("gtlcore:void_matter")
        .itemInputs("gtlcore:omni_matter", "gtlcore:pellet_antimatter")
        .inputFluids("gtceu:uu_matter 2000", "gtceu:gluons 1000")
        .itemOutputs("gtlcore:void_matter")
        .chancedOutput("gtlcore:corporeal_matter", 2000, 0)
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(400)

    gtr.ultimate_material_forge("gtlcore:temporal_matter")
        .notConsumable("gtlcore:quantum_anomaly")
        .itemInputs("gtlcore:kinetic_matter")
        .inputFluids("gtceu:uu_matter 1000", "gtceu:draconiumawakened_plasma 1000")
        .itemOutputs("gtlcore:temporal_matter")
        .chancedOutput("gtlcore:omni_matter", 500, 0)
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(600)

    gtr.ultimate_material_forge("gtlcore:dark_matter")
        .itemInputs("gtlcore:temporal_matter", "gtlcore:void_matter")
        .inputFluids("gtceu:uu_matter 3000", "gtceu:dimensionallytranscendentcrudecatalyst 1000")
        .itemOutputs("gtlcore:dark_matter")
        .chancedOutput("gtlcore:kinetic_matter", 1000, 0)
        .EUt(GTValues.VA[GTValues.MAX])
        .duration(1200)

    gtr.nano_forge("gtlcore:carbon_nanoswarm")
        .notConsumable("gtceu:lime_glass_lens")
        .itemInputs("64x gtceu:carbon_block", "64x gtceu:soc")
        .itemOutputs("64x gtceu:carbon_nanoswarm")
        .inputFluids("gtceu:soldering_alloy 20000", "gtceu:lubricant 20000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:glowstone_nanoswarm")
        .notConsumable("gtceu:orange_glass_lens")
        .itemInputs("64x minecraft:glowstone", "64x gtceu:advanced_soc")
        .itemOutputs("64x gtceu:glowstone_nanoswarm")
        .inputFluids("gtceu:uu_amplifier 10000", "gtceu:soldering_alloy 20000", "gtceu:lubricant 20000")
        .duration(16000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:copper_nanoswarm")
        .notConsumable("gtceu:brown_glass_lens")
        .itemInputs("8x minecraft:copper_block", "8x gtceu:soc")
        .itemOutputs("gtceu:copper_nanoswarm")
        .inputFluids("gtceu:naquadah 2000", "gtceu:soldering_alloy 10000", "gtceu:bismuth 10000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:iron_nanoswarm")
        .notConsumable("gtceu:gray_glass_lens")
        .itemInputs("8x minecraft:iron_block", "8x gtceu:soc")
        .itemOutputs("gtceu:iron_nanoswarm")
        .inputFluids("gtceu:naquadah 2000", "gtceu:soldering_alloy 10000", "gtceu:bismuth 10000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:gold_nanoswarm")
        .notConsumable("gtceu:yellow_glass_lens")
        .itemInputs("8x minecraft:gold_block", "16x gtceu:soc")
        .itemOutputs("gtceu:gold_nanoswarm")
        .inputFluids("gtceu:enriched_naquadah 2000", "gtceu:soldering_alloy 20000", "gtceu:bismuth 20000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:silver_nanoswarm")
        .notConsumable("gtceu:light_gray_glass_lens")
        .itemInputs("8x gtceu:silver_block", "16x gtceu:soc")
        .itemOutputs("gtceu:silver_nanoswarm")
        .inputFluids("gtceu:enriched_naquadah 2000", "gtceu:soldering_alloy 20000", "gtceu:bismuth 20000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:iridium_nanoswarm")
        .notConsumable("gtceu:glass_lens")
        .itemInputs("8x gtceu:iridium_block", "32x gtceu:soc")
        .itemOutputs("gtceu:iridium_nanoswarm")
        .inputFluids("gtceu:naquadria 2000", "gtceu:hafnium 8000", "gtceu:soldering_alloy 20000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:osmium_nanoswarm")
        .notConsumable("gtceu:diamond_lens")
        .itemInputs("8x gtceu:osmium_block", "32x gtceu:soc")
        .itemOutputs("gtceu:osmium_nanoswarm")
        .inputFluids("gtceu:naquadria 2000", "gtceu:hafnium 8000", "gtceu:soldering_alloy 20000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:rhenium_nanoswarm")
        .notConsumable("gtceu:cyan_glass_lens")
        .itemInputs("8x gtceu:rhenium_block", "64x gtceu:soc")
        .itemOutputs("gtceu:rhenium_nanoswarm")
        .inputFluids("gtceu:naquadria 2000", "gtceu:uu_amplifier 2000", "gtceu:soldering_alloy 20000")
        .duration(8000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:naquadah_nanoswarm")
        .notConsumable("gtceu:emerald_lens")
        .itemInputs("8x gtceu:naquadah_block", "16x gtceu:advanced_soc")
        .itemOutputs("gtceu:naquadah_nanoswarm")
        .inputFluids("gtceu:naquadria 8000", "gtceu:uu_amplifier 2000", "gtceu:mutated_living_solder 20000")
        .duration(16000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:neutronium_nanoswarm")
        .notConsumable("gtceu:nether_star_lens")
        .itemInputs("8x gtceu:neutronium_block", "64x gtceu:soc", "32x gtceu:advanced_soc")
        .itemOutputs("gtceu:neutronium_nanoswarm")
        .inputFluids("gtceu:neutronium 4000", "gtceu:uu_amplifier 2000", "gtceu:mutated_living_solder 20000")
        .duration(32000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:orichalcum_nanoswarm")
        .notConsumable("gtceu:magenta_glass_lens")
        .itemInputs("8x gtceu:orichalcum_block", "64x gtceu:advanced_soc", "64x gtceu:advanced_soc")
        .itemOutputs("gtceu:orichalcum_nanoswarm")
        .inputFluids("gtceu:neutronium 8000", "gtceu:uu_amplifier 4000", "gtceu:mutated_living_solder 40000")
        .duration(32000)
        .EUt(GTValues.VA[GTValues.UV])
        .addData("nano_forge_tier", 1)

    gtr.nano_forge("gtlcore:enderium_nanoswarm")
        .notConsumable("gtceu:green_glass_lens")
        .itemInputs("8x gtceu:enderium_block", "64x gtceu:advanced_soc", "64x gtceu:advanced_soc")
        .itemOutputs("gtceu:enderium_nanoswarm")
        .inputFluids("gtceu:neutronium 8000", "gtceu:uu_amplifier 4000", "gtceu:mutated_living_solder 40000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtlcore:infuscolium_nanoswarm")
        .notConsumable("gtceu:pink_glass_lens")
        .itemInputs("8x gtceu:infuscolium_block", "64x gtceu:advanced_soc", "32x gtceu:highly_advanced_soc")
        .itemOutputs("gtceu:infuscolium_nanoswarm")
        .inputFluids("gtceu:neutronium 8000", "gtceu:uu_amplifier 4000", "gtceu:mutated_living_solder 40000")
        .duration(2000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtlcore:uruium_nanoswarm")
        .notConsumable("gtceu:light_blue_glass_lens")
        .itemInputs("8x gtceu:uruium_block", "64x gtceu:advanced_soc", "64x gtceu:highly_advanced_soc")
        .itemOutputs("gtceu:uruium_nanoswarm")
        .inputFluids("gtceu:uu_matter 20000", "gtceu:mutated_living_solder 40000", "gtceu:super_mutated_living_solder 40000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtlcore:vibranium_nanoswarm")
        .notConsumable("gtceu:light_blue_glass_lens")
        .itemInputs("8x gtceu:vibranium_block", "64x gtceu:highly_advanced_soc", "64x gtceu:highly_advanced_soc")
        .itemOutputs("gtceu:vibranium_nanoswarm")
        .inputFluids("gtceu:uu_matter 20000", "gtceu:mutated_living_solder 40000", "gtceu:super_mutated_living_solder 40000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtlcore:starmetal_nanoswarm")
        .notConsumable("gtceu:red_glass_lens")
        .itemInputs("8x gtceu:starmetal_block", "64x gtceu:highly_advanced_soc", "64x gtceu:highly_advanced_soc", "64x gtceu:exquisite_glass_gem", "64x gtceu:exquisite_amethyst_gem")
        .itemOutputs("gtceu:starmetal_nanoswarm")
        .inputFluids("gtceu:uu_matter 40000", "gtceu:mutated_living_solder 80000", "gtceu:super_mutated_living_solder 80000")
        .duration(8000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtlcore:draconium_nanoswarm")
        .notConsumable("gtceu:purple_glass_lens")
        .itemInputs("8x gtceu:draconium_block", "32x gtceu:highly_advanced_soc_wafer", "32x gtlcore:optical_ram_wafer", "32x gtlcore:optical_soc", "8x gtlcore:exotic_processing_core")
        .itemOutputs("gtceu:draconium_nanoswarm")
        .inputFluids("gtceu:uu_matter 40000", "gtceu:mutated_living_solder 80000", "gtceu:super_mutated_living_solder 80000")
        .duration(16000)
        .EUt(GTValues.VA[GTValues.UEV])
        .addData("nano_forge_tier", 2)

    gtr.nano_forge("gtlcore:cosmicneutronium_nanoswarm")
        .notConsumable("gtceu:black_glass_lens")
        .itemInputs("8x gtceu:cosmicneutronium_block", "32x gtlcore:optical_soc", "32x gtlcore:exotic_wafer", "16x gtlcore:cosmic_ram_wafer", "8x gtlcore:cosmic_processing_unit_core")
        .itemOutputs("gtceu:cosmicneutronium_nanoswarm")
        .inputFluids("gtceu:uu_matter 40000", "gtceu:crystalmatrix 40000", "gtceu:liquid_cosmic_mesh 40000")
        .duration(8000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)

    gtr.nano_forge("gtlcore:white_dwarf_mtter_nanoswarm")
        .notConsumable("gtceu:ruby_lens")
        .itemInputs("8x gtceu:white_dwarf_mtter_block", "8x gtlcore:cosmic_processing_unit_core")
        .itemOutputs("gtceu:white_dwarf_mtter_nanoswarm")
        .inputFluids("gtceu:uu_matter 40000", "gtceu:neutronium 40000", "gtceu:cosmic_element 40000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)

    gtr.nano_forge("gtlcore:black_dwarf_mtter_nanoswarm")
        .notConsumable("gtceu:ruby_lens")
        .itemInputs("8x gtceu:black_dwarf_mtter_block", "8x gtlcore:cosmic_processing_unit_core")
        .itemOutputs("gtceu:black_dwarf_mtter_nanoswarm")
        .inputFluids("gtceu:uu_matter 40000", "gtceu:neutronium 40000", "gtceu:cosmic_element 40000")
        .duration(4000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)

    gtr.nano_forge("gtlcore:spacetime_nanoswarm")
        .notConsumable("gtceu:sapphire_lens")
        .notConsumable("gtlcore:quantum_anomaly")
        .itemInputs("8x gtceu:spacetime_block", "4x gtlcore:eigenfolded_kerr_manifold", "16x gtlcore:supracausal_ram_wafer", "8x gtlcore:supracausal_processing_core")
        .itemOutputs("gtceu:spacetime_nanoswarm")
        .inputFluids("gtceu:uu_matter 80000", "gtceu:infinity 40000", "gtceu:temporalfluid 40000")
        .duration(8000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)

    gtr.nano_forge("gtlcore:transcendentmetal_nanoswarm")
        .notConsumable("kubejs:non_linear_optical_lens")
        .notConsumable("gtlcore:hypercube")
        .itemInputs("gtceu:rhenium_nanoswarm", "8x gtceu:transcendentmetal_block", "8x gtlcore:recursively_folded_negative_space", "#gtceu:circuits/max")
        .itemOutputs("gtceu:transcendentmetal_nanoswarm")
        .inputFluids("gtceu:uu_matter 80000", "gtceu:raw_star_matter_plasma 40000", "gtceu:spatialfluid 20000")
        .duration(16000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)

    gtr.nano_forge("gtlcore:eternity_nanoswarm")
        .notConsumable("gtceu:blue_glass_lens")
        .notConsumable("gtlcore:quantum_anomaly")
        .notConsumable("gtlcore:eternity_catalyst")
        .itemInputs("gtceu:neutronium_nanoswarm", "8x gtceu:eternity_block", "8x gtlcore:ctc_computational_unit")
        .itemOutputs("gtceu:eternity_nanoswarm")
        .inputFluids("gtceu:spatialfluid 80000", "gtceu:exciteddtsc 80000", "gtceu:primordialmatter 80000")
        .duration(64000)
        .EUt(GTValues.VA[GTValues.UXV])
        .addData("nano_forge_tier", 3)
})