ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.laser_engraver("gtlcore:fullerene_dust")
        .itemInputs("gtceu:unfolded_fullerene_dust")
        .notConsumable("gtceu:ruby_lens")
        .inputFluids("gtceu:nitrogen 10000")
        .itemOutputs("gtceu:fullerene_dust")
        .outputFluids("gtceu:ammonia 10000")
        .EUt(2000000)
        .duration(400)
        .addDataBool("special", true)

    gtr.laser_engraver("gtlcore:lanthanum_embedded_fullerene_dust")
        .itemInputs("2x gtceu:lanthanum_fullerene_mix_dust")
        .notConsumable("gtceu:sapphire_lens")
        .inputFluids("gtceu:nitrogen 10000")
        .itemOutputs("2x gtceu:lanthanum_embedded_fullerene_dust")
        .outputFluids("gtceu:ammonia 10000")
        .EUt(1966080)
        .duration(320)
        .addDataBool("special", true)

    gtr.laser_engraver("gtlcore:singularity")
        .itemInputs("16x gtceu:magmatter_block")
        .itemInputs(Item.of("avaritia:singularity", `{Id:"avaritia:spacetime"}`).weakNBT())
        .itemOutputs("avaritia:singularity")
        .EUt(GTValues.VA[GTValues.MAX] * 262144)
        .duration(1600)

    gtr.laser_engraver("gtlcore:exotic_wafer")
        .notConsumable("gtceu:magenta_glass_lens")
        .itemInputs("gtceu:highly_advanced_soc_wafer")
        .itemOutputs("gtlcore:exotic_wafer")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(600)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:diffractor_grating_mirror")
        .itemInputs("gtlcore:photocoated_hassium_wafer")
        .notConsumable("gtlcore:grating_lithography_mask")
        .itemOutputs("gtlcore:diffractor_grating_mirror")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(600)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:ilc_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/red")
        .itemOutputs("64x gtceu:ilc_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:ram_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/green")
        .itemOutputs("64x gtceu:ram_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:lpic_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/orange")
        .itemOutputs("64x gtceu:lpic_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:simple_soc_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/cyan")
        .itemOutputs("64x gtceu:simple_soc_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:ulpic_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/blue")
        .itemOutputs("64x gtceu:ulpic_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:cpu_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/light_blue")
        .itemOutputs("64x gtceu:cpu_wafer")
        .EUt(122880)
        .duration(13)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:soc_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/yellow")
        .itemOutputs("32x gtceu:soc_wafer")
        .EUt(122880)
        .duration(50)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:nor_memory_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/pink")
        .itemOutputs("32x gtceu:nor_memory_wafer")
        .EUt(122880)
        .duration(50)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:mpic_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/brown")
        .itemOutputs("32x gtceu:mpic_wafer")
        .EUt(122880)
        .duration(50)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:nand_memory_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/gray")
        .itemOutputs("32x gtceu:nand_memory_wafer")
        .EUt(122880)
        .duration(50)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:advanced_soc_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/purple")
        .itemOutputs("8x gtceu:advanced_soc_wafer")
        .EUt(122880)
        .duration(125)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.laser_engraver("gtlcore:highly_advanced_soc_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/black")
        .itemOutputs("4x gtceu:highly_advanced_soc_wafer")
        .EUt(122880)
        .duration(225)
        .cleanroom(CleanroomType.CLEANROOM)

    gtr.precision_laser_engraver("gtlcore:prepared_cosmic_soc_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("gtlcore:lithography_mask")
        .notConsumable("#forge:lenses/yellow")
        .notConsumable("#forge:lenses/lime")
        .notConsumable("#forge:lenses/light_blue")
        .notConsumable("#forge:lenses/cyan")
        .notConsumable("#forge:lenses/purple")
        .notConsumable("#forge:lenses/black")
        .notConsumable("#forge:lenses/blue")
        .inputFluids("gtceu:gamma_rays_photoresist 1000")
        .itemOutputs("gtlcore:prepared_cosmic_soc_wafer")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(4800)
        .CWUt(1024)

    gtr.precision_laser_engraver("gtlcore:high_precision_crystal_soc")
        .itemInputs("gtceu:crystal_soc")
        .notConsumable("gtlcore:lithography_mask")
        .notConsumable("#forge:lenses/yellow")
        .notConsumable("#forge:lenses/lime")
        .notConsumable("#forge:lenses/light_blue")
        .notConsumable("#forge:lenses/cyan")
        .notConsumable("#forge:lenses/purple")
        .notConsumable("#forge:lenses/black")
        .notConsumable("#forge:lenses/blue")
        .inputFluids("gtceu:euv_photoresist 1000")
        .itemOutputs("gtlcore:high_precision_crystal_soc")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2400)
        .CWUt(256)

    gtr.precision_laser_engraver("gtlcore:nm_wafer")
        .itemInputs("gtlcore:rutherfordium_neutronium_wafer")
        .notConsumable("gtlcore:lithography_mask")
        .notConsumable("#forge:lenses/blue")
        .notConsumable("#forge:lenses/brown")
        .notConsumable("#forge:lenses/orange")
        .notConsumable("#forge:lenses/red")
        .notConsumable("gtceu:lime_glass_lens")
        .notConsumable("#forge:lenses/pink")
        .notConsumable("#forge:lenses/gray")
        .inputFluids("gtceu:photoresist 1000")
        .itemOutputs("gtlcore:nm_wafer")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(900)
        .CWUt(128)

    gtr.precision_laser_engraver("gtlcore:pm_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("gtlcore:lithography_mask")
        .notConsumable("#forge:lenses/blue")
        .notConsumable("#forge:lenses/brown")
        .notConsumable("#forge:lenses/orange")
        .notConsumable("#forge:lenses/red")
        .notConsumable("gtceu:lime_glass_lens")
        .notConsumable("#forge:lenses/pink")
        .notConsumable("#forge:lenses/gray")
        .inputFluids("gtceu:euv_photoresist 1000")
        .itemOutputs("gtlcore:pm_wafer")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(1800)
        .CWUt(256)

    gtr.precision_laser_engraver("gtlcore:fm_wafer")
        .itemInputs("gtlcore:pm_wafer")
        .notConsumable("gtlcore:grating_lithography_mask")
        .notConsumable("#forge:lenses/blue")
        .notConsumable("#forge:lenses/brown")
        .notConsumable("#forge:lenses/orange")
        .notConsumable("#forge:lenses/red")
        .notConsumable("gtceu:lime_glass_lens")
        .notConsumable("#forge:lenses/pink")
        .notConsumable("#forge:lenses/gray")
        .inputFluids("gtceu:gamma_rays_photoresist 1000")
        .itemOutputs("gtlcore:fm_wafer")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2800)
        .CWUt(512)

    gtr.precision_laser_engraver("gtlcore:raw_photon_carrying_wafer")
        .itemInputs("gtlcore:rutherfordium_neutronium_wafer")
        .notConsumable("gtlcore:lithography_mask")
        .notConsumable("#forge:lenses/light_gray")
        .notConsumable("#forge:lenses/purple")
        .notConsumable("#forge:lenses/yellow")
        .notConsumable("#forge:lenses/magenta")
        .notConsumable("#forge:lenses/orange")
        .notConsumable("#forge:lenses/light_blue")
        .notConsumable("#forge:lenses/pink")
        .itemOutputs("gtlcore:raw_photon_carrying_wafer")
        .inputFluids("gtceu:photoresist 1000")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(600)
        .CWUt(128)

    gtr.dimensional_focus_engraving_array("gtlcore:raw_photon_carrying_wafer")
        .itemInputs("gtlcore:rutherfordium_neutronium_wafer")
        .notConsumable("#forge:lenses/yellow")
        .inputFluids("gtceu:photoresist 100")
        .itemOutputs("gtlcore:raw_photon_carrying_wafer")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(600)
        .CWUt(1)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtlcore:raw_photon_carrying_wafer"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(2400))

    gtr.dimensional_focus_engraving_array("gtlcore:prepared_cosmic_soc_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/light_blue")
        .inputFluids("gtceu:gamma_rays_photoresist 100")
        .itemOutputs("gtlcore:prepared_cosmic_soc_wafer")
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(4800)
        .CWUt(8)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtlcore:prepared_cosmic_soc_wafer"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UIV])
        .duration(2400))

    gtr.dimensional_focus_engraving_array("gtlcore:high_precision_crystal_soc")
        .itemInputs("gtceu:crystal_soc")
        .notConsumable("#forge:lenses/lime")
        .inputFluids("gtceu:euv_photoresist 100")
        .itemOutputs("gtlcore:high_precision_crystal_soc")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2400)
        .CWUt(2)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtlcore:high_precision_crystal_soc"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2400))

    gtr.dimensional_focus_engraving_array("gtlcore:nm_wafer")
        .itemInputs("gtlcore:rutherfordium_neutronium_wafer")
        .notConsumable("#forge:lenses/blue")
        .inputFluids("gtceu:photoresist 100")
        .itemOutputs("gtlcore:nm_wafer")
        .EUt(GTValues.VA[GTValues.UV])
        .duration(900)
        .CWUt(1)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtlcore:nm_wafer"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UV])
        .duration(2400))

    gtr.dimensional_focus_engraving_array("gtlcore:pm_wafer")
        .itemInputs("gtlcore:taranium_wafer")
        .notConsumable("#forge:lenses/magenta")
        .inputFluids("gtceu:euv_photoresist 100")
        .itemOutputs("gtlcore:pm_wafer")
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(1800)
        .CWUt(2)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtlcore:pm_wafer"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UHV])
        .duration(2400))

    gtr.dimensional_focus_engraving_array("gtlcore:fm_wafer")
        .itemInputs("gtlcore:pm_wafer")
        .notConsumable("#forge:lenses/orange")
        .inputFluids("gtceu:gamma_rays_photoresist 100")
        .itemOutputs("gtlcore:fm_wafer")
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2700)
        .CWUt(4)
    ["scannerResearch(java.util.function.UnaryOperator)"](b => b.researchStack(Registries.getItemStack("gtlcore:fm_wafer"))
        .dataStack(Registries.getItemStack("gtceu:data_module"))
        .EUt(GTValues.VA[GTValues.UEV])
        .duration(2400))
})