disableDrift: true

enablePrimitiveVoidOre: false

oreMultiplier: 4

cellType: 4

spacetimePip: 2147483647

durationMultiplier: 1.0

eioFluidRate: 16

# 更大的数值会让界面显示有问题，推荐在样板管理终端管理
exPatternProvider: 36

mobList1:
  - minecraft:chicken
  - minecraft:rabbit
  - minecraft:sheep
  - minecraft:cow
  - minecraft:horse
  - minecraft:pig
  - minecraft:donkey
  - minecraft:skeleton_horse
  - minecraft:iron_golem
  - minecraft:wolf
  - minecraft:goat
  - minecraft:parrot
  - minecraft:camel
  - minecraft:cat
  - minecraft:fox
  - minecraft:llama
  - minecraft:panda
  - minecraft:polar_bear

mobList2:
  - minecraft:ghast
  - minecraft:zombie
  - minecraft:pillager
  - minecraft:zombie_villager
  - minecraft:skeleton
  - minecraft:drowned
  - minecraft:witch
  - minecraft:spider
  - minecraft:creeper
  - minecraft:husk
  - minecraft:wither_skeleton
  - minecraft:blaze
  - minecraft:zombified_piglin
  - minecraft:slime
  - minecraft:vindicator
  - minecraft:enderman

